# This is a basic workflow to help you get started with Actions

name: thirdweb-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  thirdweb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      publish_output: ${{ steps.publish.outputs.stdout }}
      deploy_output: ${{ steps.deploy.outputs.stdout }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

        # setup your project
      - uses: actions/setup-node@v3
      #- uses: actions/foundry-toolchain

        # Set up your build here:
      - run: yarn
      #-run: forge install

      - name: deploy
        id: deploy
        if: github.event_name == 'pull_request' || github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          DEPLOY=$(npx thirdweb deploy)
          echo "::set-output name=stdout::$DEPLOY"
      - name: publish
        id: publish
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          PUBLISH=$(npx thirdweb publish)
          echo "::set-output name=stdout::$PUBLISH"

  notify:
    runs-on: ubuntu-latest
    needs: [thirdweb]
    steps:
      - name: thirdweb dashboard url comment
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            ${{ needs.thirdweb.outputs.publish_output }}
            ${{ needs.thirdweb.outputs.deploy_output }}
