name: thirdweb

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy_output: ${{ steps.deploy.outputs.stdout }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: deploy
        if: github.event_name == 'pull_request' || github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        id: deploy
        run: |
          DEPLOY=$(npx @thirdweb-dev/cli@dev deploy --ci | grep http)
          echo "::set-output name=stdout::$DEPLOY"

  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      publish_output: ${{ steps.publish.outputs.stdout }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: publish
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        id: publish
        run: |
          PUBLISH=$(npx @thirdweb-dev/cli@dev publish --ci | grep http)
          echo "::set-output name=stdout::$PUBLISH"


  comment_on_commit:
    runs-on: ubuntu-latest
    needs: [deploy, publish]
    if: github.event_name == 'push'
    steps:
      - name: Comment on commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            Contract compiled, deploy using the button below
            <p>
            <a href="${{ needs.thirdweb.outputs.publish_output }}${{ needs.thirdweb.outputs.deploy_output }}"><img width="200px" src="https://gateway.thirdweb.dev/ipfs/QmZdGx8gd5sKyQeaxqDvpH7KNFiHF7zRjzPysPGW8TGYqN/0.svg" /></a>
          token: ${{ secrets.GITHUB_TOKEN }}

  comment_on_pr:
    runs-on: ubuntu-latest
    needs: [deploy, publish]
    if: github.event_name == 'pull_request'
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Contract compiled, deploy using the button below
            <p>
            <a href="${{ needs.thirdweb.outputs.publish_output }}${{ needs.thirdweb.outputs.deploy_output }}"><img width="200px" src="https://gateway.thirdweb.dev/ipfs/QmZdGx8gd5sKyQeaxqDvpH7KNFiHF7zRjzPysPGW8TGYqN/0.svg" /></a>
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
